# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 4.0

# Default target executed when no arguments are given to make.
default_target: all
.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:

#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:

# Disable VCS-based implicit rules.
% : %,v

# Disable VCS-based implicit rules.
% : RCS/%

# Disable VCS-based implicit rules.
% : RCS/%,v

# Disable VCS-based implicit rules.
% : SCCS/s.%

# Disable VCS-based implicit rules.
% : s.%

.SUFFIXES: .hpux_make_needs_suffix_list

# Command-line flag to silence nested $(MAKE).
$(VERBOSE)MAKESILENT = -s

#Suppress display of executed commands.
$(VERBOSE).SILENT:

# A target that is always out of date.
cmake_force:
.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /opt/homebrew/bin/cmake

# The command to remove a file.
RM = /opt/homebrew/bin/cmake -E rm -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /Users/azrafsakeef/Documents/GTEST

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /Users/azrafsakeef/Documents/GTEST/build

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Running CMake cache editor..."
	/opt/homebrew/bin/ccmake -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache
.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Running CMake to regenerate build system..."
	/opt/homebrew/bin/cmake --regenerate-during-build -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache
.PHONY : rebuild_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /Users/azrafsakeef/Documents/GTEST/build/CMakeFiles /Users/azrafsakeef/Documents/GTEST/build//CMakeFiles/progress.marks
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /Users/azrafsakeef/Documents/GTEST/build/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean
.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named ShapeFactoryProject

# Build rule for target.
ShapeFactoryProject: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 ShapeFactoryProject
.PHONY : ShapeFactoryProject

# fast build rule for target.
ShapeFactoryProject/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ShapeFactoryProject.dir/build.make CMakeFiles/ShapeFactoryProject.dir/build
.PHONY : ShapeFactoryProject/fast

src/ShapeFactory.o: src/ShapeFactory.cpp.o
.PHONY : src/ShapeFactory.o

# target to build an object file
src/ShapeFactory.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ShapeFactoryProject.dir/build.make CMakeFiles/ShapeFactoryProject.dir/src/ShapeFactory.cpp.o
.PHONY : src/ShapeFactory.cpp.o

src/ShapeFactory.i: src/ShapeFactory.cpp.i
.PHONY : src/ShapeFactory.i

# target to preprocess a source file
src/ShapeFactory.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ShapeFactoryProject.dir/build.make CMakeFiles/ShapeFactoryProject.dir/src/ShapeFactory.cpp.i
.PHONY : src/ShapeFactory.cpp.i

src/ShapeFactory.s: src/ShapeFactory.cpp.s
.PHONY : src/ShapeFactory.s

# target to generate assembly for a file
src/ShapeFactory.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ShapeFactoryProject.dir/build.make CMakeFiles/ShapeFactoryProject.dir/src/ShapeFactory.cpp.s
.PHONY : src/ShapeFactory.cpp.s

src/run_shapes.o: src/run_shapes.cpp.o
.PHONY : src/run_shapes.o

# target to build an object file
src/run_shapes.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ShapeFactoryProject.dir/build.make CMakeFiles/ShapeFactoryProject.dir/src/run_shapes.cpp.o
.PHONY : src/run_shapes.cpp.o

src/run_shapes.i: src/run_shapes.cpp.i
.PHONY : src/run_shapes.i

# target to preprocess a source file
src/run_shapes.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ShapeFactoryProject.dir/build.make CMakeFiles/ShapeFactoryProject.dir/src/run_shapes.cpp.i
.PHONY : src/run_shapes.cpp.i

src/run_shapes.s: src/run_shapes.cpp.s
.PHONY : src/run_shapes.s

# target to generate assembly for a file
src/run_shapes.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ShapeFactoryProject.dir/build.make CMakeFiles/ShapeFactoryProject.dir/src/run_shapes.cpp.s
.PHONY : src/run_shapes.cpp.s

test/ShapeFactoryTest.o: test/ShapeFactoryTest.cpp.o
.PHONY : test/ShapeFactoryTest.o

# target to build an object file
test/ShapeFactoryTest.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ShapeFactoryProject.dir/build.make CMakeFiles/ShapeFactoryProject.dir/test/ShapeFactoryTest.cpp.o
.PHONY : test/ShapeFactoryTest.cpp.o

test/ShapeFactoryTest.i: test/ShapeFactoryTest.cpp.i
.PHONY : test/ShapeFactoryTest.i

# target to preprocess a source file
test/ShapeFactoryTest.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ShapeFactoryProject.dir/build.make CMakeFiles/ShapeFactoryProject.dir/test/ShapeFactoryTest.cpp.i
.PHONY : test/ShapeFactoryTest.cpp.i

test/ShapeFactoryTest.s: test/ShapeFactoryTest.cpp.s
.PHONY : test/ShapeFactoryTest.s

# target to generate assembly for a file
test/ShapeFactoryTest.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ShapeFactoryProject.dir/build.make CMakeFiles/ShapeFactoryProject.dir/test/ShapeFactoryTest.cpp.s
.PHONY : test/ShapeFactoryTest.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... edit_cache"
	@echo "... rebuild_cache"
	@echo "... ShapeFactoryProject"
	@echo "... src/ShapeFactory.o"
	@echo "... src/ShapeFactory.i"
	@echo "... src/ShapeFactory.s"
	@echo "... src/run_shapes.o"
	@echo "... src/run_shapes.i"
	@echo "... src/run_shapes.s"
	@echo "... test/ShapeFactoryTest.o"
	@echo "... test/ShapeFactoryTest.i"
	@echo "... test/ShapeFactoryTest.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

