# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 4.0

# Default target executed when no arguments are given to make.
default_target: all
.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:

#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:

# Disable VCS-based implicit rules.
% : %,v

# Disable VCS-based implicit rules.
% : RCS/%

# Disable VCS-based implicit rules.
% : RCS/%,v

# Disable VCS-based implicit rules.
% : SCCS/s.%

# Disable VCS-based implicit rules.
% : s.%

.SUFFIXES: .hpux_make_needs_suffix_list

# Command-line flag to silence nested $(MAKE).
$(VERBOSE)MAKESILENT = -s

#Suppress display of executed commands.
$(VERBOSE).SILENT:

# A target that is always out of date.
cmake_force:
.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /opt/homebrew/bin/cmake

# The command to remove a file.
RM = /opt/homebrew/bin/cmake -E rm -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /Users/azrafsakeef/Documents/GTEST

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /Users/azrafsakeef/Documents/GTEST/build

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Running CMake cache editor..."
	/opt/homebrew/bin/ccmake -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache
.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Running CMake to regenerate build system..."
	/opt/homebrew/bin/cmake --regenerate-during-build -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache
.PHONY : rebuild_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /Users/azrafsakeef/Documents/GTEST/build/CMakeFiles /Users/azrafsakeef/Documents/GTEST/build//CMakeFiles/progress.marks
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /Users/azrafsakeef/Documents/GTEST/build/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean
.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named VehicleFactoryProject

# Build rule for target.
VehicleFactoryProject: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 VehicleFactoryProject
.PHONY : VehicleFactoryProject

# fast build rule for target.
VehicleFactoryProject/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/VehicleFactoryProject.dir/build.make CMakeFiles/VehicleFactoryProject.dir/build
.PHONY : VehicleFactoryProject/fast

src/Bike.o: src/Bike.cpp.o
.PHONY : src/Bike.o

# target to build an object file
src/Bike.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/VehicleFactoryProject.dir/build.make CMakeFiles/VehicleFactoryProject.dir/src/Bike.cpp.o
.PHONY : src/Bike.cpp.o

src/Bike.i: src/Bike.cpp.i
.PHONY : src/Bike.i

# target to preprocess a source file
src/Bike.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/VehicleFactoryProject.dir/build.make CMakeFiles/VehicleFactoryProject.dir/src/Bike.cpp.i
.PHONY : src/Bike.cpp.i

src/Bike.s: src/Bike.cpp.s
.PHONY : src/Bike.s

# target to generate assembly for a file
src/Bike.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/VehicleFactoryProject.dir/build.make CMakeFiles/VehicleFactoryProject.dir/src/Bike.cpp.s
.PHONY : src/Bike.cpp.s

src/Car.o: src/Car.cpp.o
.PHONY : src/Car.o

# target to build an object file
src/Car.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/VehicleFactoryProject.dir/build.make CMakeFiles/VehicleFactoryProject.dir/src/Car.cpp.o
.PHONY : src/Car.cpp.o

src/Car.i: src/Car.cpp.i
.PHONY : src/Car.i

# target to preprocess a source file
src/Car.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/VehicleFactoryProject.dir/build.make CMakeFiles/VehicleFactoryProject.dir/src/Car.cpp.i
.PHONY : src/Car.cpp.i

src/Car.s: src/Car.cpp.s
.PHONY : src/Car.s

# target to generate assembly for a file
src/Car.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/VehicleFactoryProject.dir/build.make CMakeFiles/VehicleFactoryProject.dir/src/Car.cpp.s
.PHONY : src/Car.cpp.s

src/Truck.o: src/Truck.cpp.o
.PHONY : src/Truck.o

# target to build an object file
src/Truck.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/VehicleFactoryProject.dir/build.make CMakeFiles/VehicleFactoryProject.dir/src/Truck.cpp.o
.PHONY : src/Truck.cpp.o

src/Truck.i: src/Truck.cpp.i
.PHONY : src/Truck.i

# target to preprocess a source file
src/Truck.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/VehicleFactoryProject.dir/build.make CMakeFiles/VehicleFactoryProject.dir/src/Truck.cpp.i
.PHONY : src/Truck.cpp.i

src/Truck.s: src/Truck.cpp.s
.PHONY : src/Truck.s

# target to generate assembly for a file
src/Truck.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/VehicleFactoryProject.dir/build.make CMakeFiles/VehicleFactoryProject.dir/src/Truck.cpp.s
.PHONY : src/Truck.cpp.s

src/VehicleFactory.o: src/VehicleFactory.cpp.o
.PHONY : src/VehicleFactory.o

# target to build an object file
src/VehicleFactory.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/VehicleFactoryProject.dir/build.make CMakeFiles/VehicleFactoryProject.dir/src/VehicleFactory.cpp.o
.PHONY : src/VehicleFactory.cpp.o

src/VehicleFactory.i: src/VehicleFactory.cpp.i
.PHONY : src/VehicleFactory.i

# target to preprocess a source file
src/VehicleFactory.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/VehicleFactoryProject.dir/build.make CMakeFiles/VehicleFactoryProject.dir/src/VehicleFactory.cpp.i
.PHONY : src/VehicleFactory.cpp.i

src/VehicleFactory.s: src/VehicleFactory.cpp.s
.PHONY : src/VehicleFactory.s

# target to generate assembly for a file
src/VehicleFactory.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/VehicleFactoryProject.dir/build.make CMakeFiles/VehicleFactoryProject.dir/src/VehicleFactory.cpp.s
.PHONY : src/VehicleFactory.cpp.s

src/main.o: src/main.cpp.o
.PHONY : src/main.o

# target to build an object file
src/main.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/VehicleFactoryProject.dir/build.make CMakeFiles/VehicleFactoryProject.dir/src/main.cpp.o
.PHONY : src/main.cpp.o

src/main.i: src/main.cpp.i
.PHONY : src/main.i

# target to preprocess a source file
src/main.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/VehicleFactoryProject.dir/build.make CMakeFiles/VehicleFactoryProject.dir/src/main.cpp.i
.PHONY : src/main.cpp.i

src/main.s: src/main.cpp.s
.PHONY : src/main.s

# target to generate assembly for a file
src/main.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/VehicleFactoryProject.dir/build.make CMakeFiles/VehicleFactoryProject.dir/src/main.cpp.s
.PHONY : src/main.cpp.s

test/VechicleFactoryTest.o: test/VechicleFactoryTest.cpp.o
.PHONY : test/VechicleFactoryTest.o

# target to build an object file
test/VechicleFactoryTest.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/VehicleFactoryProject.dir/build.make CMakeFiles/VehicleFactoryProject.dir/test/VechicleFactoryTest.cpp.o
.PHONY : test/VechicleFactoryTest.cpp.o

test/VechicleFactoryTest.i: test/VechicleFactoryTest.cpp.i
.PHONY : test/VechicleFactoryTest.i

# target to preprocess a source file
test/VechicleFactoryTest.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/VehicleFactoryProject.dir/build.make CMakeFiles/VehicleFactoryProject.dir/test/VechicleFactoryTest.cpp.i
.PHONY : test/VechicleFactoryTest.cpp.i

test/VechicleFactoryTest.s: test/VechicleFactoryTest.cpp.s
.PHONY : test/VechicleFactoryTest.s

# target to generate assembly for a file
test/VechicleFactoryTest.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/VehicleFactoryProject.dir/build.make CMakeFiles/VehicleFactoryProject.dir/test/VechicleFactoryTest.cpp.s
.PHONY : test/VechicleFactoryTest.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... edit_cache"
	@echo "... rebuild_cache"
	@echo "... VehicleFactoryProject"
	@echo "... src/Bike.o"
	@echo "... src/Bike.i"
	@echo "... src/Bike.s"
	@echo "... src/Car.o"
	@echo "... src/Car.i"
	@echo "... src/Car.s"
	@echo "... src/Truck.o"
	@echo "... src/Truck.i"
	@echo "... src/Truck.s"
	@echo "... src/VehicleFactory.o"
	@echo "... src/VehicleFactory.i"
	@echo "... src/VehicleFactory.s"
	@echo "... src/main.o"
	@echo "... src/main.i"
	@echo "... src/main.s"
	@echo "... test/VechicleFactoryTest.o"
	@echo "... test/VechicleFactoryTest.i"
	@echo "... test/VechicleFactoryTest.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

